### ISSUE TITLE
出现多余的 HTML 标签

### ISSUE THREAD

**Issue by Snownee** [imzhangshirong/Ecode#8]
![image](https://user-images.githubusercontent.com/16059084/32838474-02c1d502-ca4c-11e7-81c8-cc20a4fe59c6.png)

在 `ecode.js:143` 后添加一行调试代码

![image](https://user-images.githubusercontent.com/16059084/32838562-51df9674-ca4c-11e7-9c0d-2c63ed2245ec.png)

绘制 Demo 中的 DLL 例子

![image](https://user-images.githubusercontent.com/16059084/32838580-626796ae-ca4c-11e7-96cf-c4126ff25ebe.png)

控制台中第一行出现多余的 HTML 标签

**Comment by imzhangshirong** [comment]
3.5.10已经修复
